name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, mysql, pdo_mysql
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Create .env file
        run: |
          cp .env.example .env
          echo "APP_ENV=testing" >> .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=:memory:" >> .env
          echo "CACHE_DRIVER=array" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env
          echo "SESSION_DRIVER=array" >> .env
          echo "MAIL_MAILER=array" >> .env
          echo "PARALLEL_TESTING=true" >> .env
          echo "FILESYSTEM_DRIVER=local" >> .env
          echo "AWS_ACCESS_KEY_ID=test" >> .env
          echo "AWS_SECRET_ACCESS_KEY=test" >> .env
          echo "AWS_DEFAULT_REGION=us-east-1" >> .env
          echo "AWS_BUCKET_AVATARS=test-bucket" >> .env
          echo "AWS_ENDPOINT=http://localhost:9000" >> .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Clear Config Cache
        run: php artisan config:clear

      - name: Execute Tests
        run: vendor/bin/pest --parallel --processes=4
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
          CACHE_DRIVER: array
          QUEUE_CONNECTION: sync
          SESSION_DRIVER: array
          MAIL_MAILER: array
          PARALLEL_TESTING: "true"
          FILESYSTEM_DRIVER: local
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
          AWS_BUCKET_AVATARS: test-bucket
          AWS_ENDPOINT: http://localhost:9000
          FILESYSTEM_DRIVER: local
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
          AWS_BUCKET_AVATARS: test-bucket
          AWS_ENDPOINT: http://localhost:9000

  laravel-pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Laravel Pint"
        uses: aglipanci/laravel-pint-action@2.3.1
        with:
          testMode: true
          pintVersion: 1.18.1
